ptt_key = "RControl"
typing_delay_ms = 0
initial_delay_ms = 20
model = "whisper-1"
# language = "ru" # Uncomment to force Russian language

# Sound Settings
sound_enabled = true
sound_start_path = "/usr/share/sounds/freedesktop/stereo/audio-volume-change.oga"
sound_end_path = "/usr/share/sounds/freedesktop/stereo/screen-capture.oga"
